In [1]:
import numpy as np

In [3]:
arr=np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[1:4]

array([1, 2, 3])

In [9]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
#broadcast to first five digit
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
slice_of_arr = arr[0:6]

In [17]:
slice_of_arr[:5]

array([100, 100, 100, 100, 100])

In [25]:
arr_copy = arr.copy()

In [26]:
arr_2d = np.array([[3,4,5],[8,9,7],[43,54,64]])

In [27]:
arr_2d

array([[ 3,  4,  5],
       [ 8,  9,  7],
       [43, 54, 64]])

In [28]:
arr_2d[2][1]

54

In [31]:
arr_2d[:2,1:]

array([[4, 5],
       [9, 7]])

In [34]:
arr = np.arange(0,11)

In [36]:
bool_o = arr>5

In [37]:
bool_o

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [38]:
arr[bool_o]

array([ 6,  7,  8,  9, 10])

In [39]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [40]:
arr[arr<3]

array([0, 1, 2])

In [41]:
arr_2d = np.arange(50)

In [46]:
arr_2d = arr_2d.reshape(5,10)

In [47]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
arr_2d[:4,2:]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26, 27, 28, 29],
       [32, 33, 34, 35, 36, 37, 38, 39]])